apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: juliam-devops
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: juliam-devops
    spec:
      containers:
      - name: juliam-devops
        image: docker.io/pleungdev/juliam-devops:$BUILD_ID
        ports:
        - containerPort: 16615
---
apiVersion: v1
kind: Service
metadata:
  name: juliam-devops
spec:
  type: LoadBalancer
  ports:
  - port: 16615
  selector:
    app: juliam-devops
